OBJS	= string_ext.o linked_list.o varlst.o net.o http.o main.o config.o plugins.o script_parser.o gosucmd.o
GOUT	= ../gosu/gosu.exe
CFLAGS	= --pedantic -ansi -fexpensive-optimizations -O3 

%.o : %.c
	gcc -c $< -o $@ $(CFLAGS)

$(GOUT): $(OBJS)
	gcc $(OBJS) -o $(GOUT) -lwsock32 $(CFLAGS) -mwindows
	
